# Generated by Django 6.0.2 on 2026-02-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_urlshort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshort',
            name='created_at',
        ),
        migrations.AddField(
            model_name='urlshort',
            name='short',
            field=models.CharField(default='url', max_length=10, unique=True),
        ),
    ]
