# Generated by Django 6.0.2 on 2026-02-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_remove_urlshort_created_at_urlshort_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='short',
            field=models.CharField(default='short url', max_length=10),
        ),
    ]
