# Generated by Django 6.0.2 on 2026-02-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_urlshort_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshort',
            name='click',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
