# Generated by Django 6.0.2 on 2026-02-09 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_urlshort_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
