# Generated by Django 6.0.2 on 2026-02-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_alter_urlshort_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshort',
            name='owner',
        ),
    ]
