# Generated by Django 6.0.2 on 2026-02-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0011_urlshort_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshort',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
