# Generated by Django 6.0.2 on 2026-02-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0012_urlshort_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='short',
            field=models.CharField(default='short url', max_length=10, unique=True),
        ),
    ]
